[tox]
envlist = py38, py39, py310, py311, py312, py313
isolated_build = true
skip_missing_interpreters = true


[gh-actions]
python =
    3.12: py312

[testenv]
description = Run tests with pytest under {envname}
deps =
    pytest>=6.0
    pytest-cov
    pytest-regressions
    flake8
    black
commands =
    pytest tests/ --cov=src/str_mut_signatures --cov-report=term-missing

[testenv:py312]
deps =
    pytest
    pytest-cov
    pytest-regressions
    flake8
    black
commands = pytest --cov=strvcf_annotator --cov-report=term-missing --cov-report=xml:coverage.xml
